language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

env:
  global:
    - secure: "dEuRtU4v8qF380KUYtEztE+huLYPA1WULBGKfOuB6WDgIdZPFcrYVJbeDgjPpVEmSFXYpdM3WJF1vFOAfOI9E7Z8wX8RaLPIMSTg8bkbBY+07oxv778RTSOB1mv5oFYYwYxYHjf1A9h53r3hcoL6ov9/BWuRFjWxOpbUGkfBP/ggzOXS48krm7xcXLv+4oifSy1gs87GFtAZ8ov1p+K4yENSpv2MTL4unDEqDK+TLoy+qHrV03UU/qrOlE7bhkC7KtYF3avav4FuWQixyj8DU9OnMOtpaB78DbTBmjStUKOITzQUggHD3AunIUYQSL9miWdTqdbLZvwo2fOK3lxR8rzNOLv0XBinCSuG7JE7vnQVnuoiSDZ18CPbZWaUBXVdnhYg6q2oT/Ah/NDXiYDKfkO92B6ASWntrLzLE81Jc4PJjQxyqM5VYtQxy2OqL624UCuIWtd7bYi2SqqDVixgN6NRyoeyUrTE6uemVtOiIeM0ANvvqbc/6wwvu3jA47zZrdFpjtHmPaECnMcgbco4/An7w9DXuUmKEKd0YhIAQiXSwIbVmApUXv0w1XHUsmVaqhBQDOWwvwRByXXFDGquug/vYVfemjWficzXupzVX3JwRuspcldooedYgoF4NPDjKkXxD087HWqsnotql1G3UWIa6UKM4Kncl0EE55l7FG0="

notifications:
  email:
    on_success: never

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev; else brew install libusb; fi
  - travis_wait cargo install rustfmt --force || true

before_script:
  - export PATH="$PATH":~/.cargo/bin
  - echo "\$ rustfmt --version"
  - cargo fmt --all -- --version

script:
  # Install Janus
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get.sh | bash
  # Add Janus to PATH.
  - export PATH=$PATH:$PWD/janusbin
  - export APP_VERSION="$(janus version -format 'v%M.%m.%C-%S')"
  - export RUST_BACKTRACE=1
  - cargo fmt --all -- --verbose --write-mode=diff
  - cargo test --all --verbose
  - cargo build --all --verbose --release

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
  tags: true
